

module Gcrypt
  module ControlConstant
    #/* Note: 1 .. 2 are not anymore used. */
    GCRYCTL_CFB_SYNC = 3
    GCRYCTL_RESET    = 4   #/* e.g. for MDs */
    GCRYCTL_FINALIZE = 5
    GCRYCTL_GET_KEYLEN = 6
    GCRYCTL_GET_BLKLEN = 7
    GCRYCTL_TEST_ALGO = 8
    GCRYCTL_IS_SECURE = 9
    GCRYCTL_GET_ASNOID = 10
    GCRYCTL_ENABLE_ALGO = 11
    GCRYCTL_DISABLE_ALGO = 12
    GCRYCTL_DUMP_RANDOM_STATS = 13
    GCRYCTL_DUMP_SECMEM_STATS = 14
    GCRYCTL_GET_ALGO_NPKEY    = 15
    GCRYCTL_GET_ALGO_NSKEY    = 16
    GCRYCTL_GET_ALGO_NSIGN    = 17
    GCRYCTL_GET_ALGO_NENCR    = 18
    GCRYCTL_SET_VERBOSITY     = 19
    GCRYCTL_SET_DEBUG_FLAGS   = 20
    GCRYCTL_CLEAR_DEBUG_FLAGS = 21
    GCRYCTL_USE_SECURE_RNDPOOL= 22
    GCRYCTL_DUMP_MEMORY_STATS = 23
    GCRYCTL_INIT_SECMEM       = 24
    GCRYCTL_TERM_SECMEM       = 25
    GCRYCTL_DISABLE_SECMEM_WARN = 27
    GCRYCTL_SUSPEND_SECMEM_WARN = 28
    GCRYCTL_RESUME_SECMEM_WARN  = 29
    GCRYCTL_DROP_PRIVS          = 30
    GCRYCTL_ENABLE_M_GUARD      = 31
    GCRYCTL_START_DUMP          = 32
    GCRYCTL_STOP_DUMP           = 33
    GCRYCTL_GET_ALGO_USAGE      = 34
    GCRYCTL_IS_ALGO_ENABLED     = 35
    GCRYCTL_DISABLE_INTERNAL_LOCKING = 36
    GCRYCTL_DISABLE_SECMEM      = 37
    GCRYCTL_INITIALIZATION_FINISHED = 38
    GCRYCTL_INITIALIZATION_FINISHED_P = 39
    GCRYCTL_ANY_INITIALIZATION_P = 40
    GCRYCTL_SET_CBC_CTS = 41
    GCRYCTL_SET_CBC_MAC = 42
    #/* Note: 43 is not anymore used. */
    GCRYCTL_ENABLE_QUICK_RANDOM = 44
    GCRYCTL_SET_RANDOM_SEED_FILE = 45
    GCRYCTL_UPDATE_RANDOM_SEED_FILE = 46
    GCRYCTL_SET_THREAD_CBS = 47
    GCRYCTL_FAST_POLL = 48
    GCRYCTL_SET_RANDOM_DAEMON_SOCKET = 49
    GCRYCTL_USE_RANDOM_DAEMON = 50
    GCRYCTL_FAKED_RANDOM_P = 51
    GCRYCTL_SET_RNDEGD_SOCKET = 52
    GCRYCTL_PRINT_CONFIG = 53
    GCRYCTL_OPERATIONAL_P = 54
    GCRYCTL_FIPS_MODE_P = 55
    GCRYCTL_FORCE_FIPS_MODE = 56
    GCRYCTL_SELFTEST = 57
    #/* Note: 58 .. 62 are used internally.  */
    GCRYCTL_DISABLE_HWF = 63
    GCRYCTL_SET_ENFORCED_FIPS_FLAG = 64
    GCRYCTL_SET_PREFERRED_RNG_TYPE = 65
    GCRYCTL_GET_CURRENT_RNG_TYPE = 66
    GCRYCTL_DISABLE_LOCKED_SECMEM = 67
    GCRYCTL_DISABLE_PRIV_DROP = 68
    GCRYCTL_SET_CCM_LENGTHS = 69
    GCRYCTL_CLOSE_RANDOM_DEVICE = 70
    GCRYCTL_INACTIVATE_FIPS_FLAG = 71
    GCRYCTL_REACTIVATE_FIPS_FLAG = 72
    GCRYCTL_SET_SBOX = 73
    GCRYCTL_DRBG_REINIT = 74
    GCRYCTL_SET_TAGLEN = 75
    GCRYCTL_GET_TAGLEN = 76
    GCRYCTL_REINIT_SYSCALL_CLAMP = 77


  end
end
